name: Release package to github packages
on:
  release:
    types: [published]
permissions:
  contents: read
  packages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Append to npmrc
        run: |
          echo -e "\n//npm.pkg.github.com/:_authToken=$PACKAGES_UPLOAD_PAT" >> .npmrc
        env:
          PACKAGES_UPLOAD_PAT: ${{ secrets.PACKAGES_UPLOAD_PAT }}
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: 16
          token: ${{ secrets.PACKAGES_UPLOAD_PAT }}
      - run: npm install --no-save
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_UPLOAD_PAT }}
