name: Run unit tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['15', '16']
    steps:
      - uses: actions/checkout@v2
      - name: Append to npmrc
        run: |
          echo -e "\n//npm.pkg.github.com/:_authToken=$PACKAGES_UPLOAD_PAT" >> .npmrc
          cat .npmrc
        env:
          PACKAGES_UPLOAD_PAT: ${{ secrets.PACKAGES_UPLOAD_PAT }}
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
          node-version: ${{ matrix.node }}
      - run: npm install --no-save
